/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109404-g07e0732a9a-20221211"
#endif /* AVUTIL_FFVERSION_H */
